bbmachine/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('subdiscovery/', include('subdiscovery.urls')),
    path('admin/', admin.site.urls),
]

subdiscovery/urls.py
from django.urls import path

from . import views

app_name = 'subdiscovery'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('find_subdomains/', views.find_subdomains_view, name='find_subdomains'),
    path('domain/<int:pk>/', views.DomainView.as_view(), name='domain'),
    #path('subdomain/<int:pk>/', views.SubdomainView.as_view(), name='subdomain'),
    path('add_domain/', views.AddDomainView.as_view(), name='add_domain'),
    path('domain_confirm_delete/<int:pk>/', views.DomainDelete.as_view(), name='domain_delete'),
]

subdiscovery/models.py
from django.db import models

class Domain(models.Model):
    name = models.CharField(max_length=253)

    def __str__(self):
        return self.name

class Subdomain(models.Model):
    name = models.CharField(max_length=253)
    domain = models.ForeignKey(Domain, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

subdiscovery/forms.py
from django import forms

class AddDomainForm(forms.Form):
    name = forms.CharField(label='Domain name', max_length=100)

subdiscovery/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.views import generic, View

from .forms import AddDomainForm
from .models import Domain, Subdomain
from utils import send_slack_notification
import requests
import subprocess
#from . import find_subdomains
from subdiscovery.tasks import find_subdomains

import os

class IndexView(generic.ListView):
    template_name = 'subdiscovery/index.html'
    model = Domain
    context_object_name = 'domains'

def find_subdomains_view(request):
    find_subdomains.delay();
    return redirect('subdiscovery:index')

class DomainView(View):
    def get(self, request, pk):
        domain = get_object_or_404(Domain, pk=pk)
        subdomains = Subdomain.objects.filter(domain=domain)
        return render(request, 'subdiscovery/domain.html', {'domain': domain, 'subdomains': subdomains})

class AddDomainView(generic.edit.CreateView):
    template_name = 'subdiscovery/add_domain.html'
    model = Domain
    fields = ['name']
    success_url = reverse_lazy('subdiscovery:index')

class DomainDelete(generic.edit.DeleteView):
    template_name = 'subdiscovery/domain_confirm_delete.html'
    model = Domain
    success_url = reverse_lazy('subdiscovery:index')

subdiscovery/templates/subdiscovery/add_domain.html
<h1>ADD DOMAIN FORM</h1>
<form method='POST'>
    {% csrf_token %}
    {{ form }}
    <input type='submit' value='Add'>
</form>

subdiscovery/templates/subdiscovery/domain.html
<h1>Subdomains found for {{ domain }} ({{ subdomains|length }})</h1>
<a href="{% url 'subdiscovery:domain_delete' domain.pk %}">Delete</a>
<ul>
{% for subdomain in subdomains %}    
<li>{{ subdomain }}</li>
{% endfor %}
</ul>

subdiscovery/templates/subdiscovery/domain_confirm_delete.html
<form method='POST'>
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ domain }}"?</p>
    <input type='submit' value='Confirm'>
</form>

subdiscovery/templates/subdiscovery/index.html
<h1>Domains:</h1>
{% if domains %}    
    <ul>
    {% for domain in domains %}
    <li><a href="{% url 'subdiscovery:domain' domain.id %}">{{domain}}</a></li>
    {% endfor %}
    </ul>
{% endif %}

<a href='/subdiscovery/add_domain'>Add domain</button>
</br>
</br>
<a href="{% url 'subdiscovery:find_subdomains' %}">Find subdomains</a>